name = "OptimalTrajectoryGeneration"
uuid = "fea8e896-a1ec-43ab-b3f1-27ee766c5235"
authors = ["Michael Kuts", "Yuriy Zasypkin"]
version = "1.0.0-DEV"

[compat]
julia = "1.11"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
