name = "OptimalTrajectoryGeneration"
uuid = "fea8e896-a1ec-43ab-b3f1-27ee766c5235"
authors = ["Michael Kuts", "Yuriy Zasypkin"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[compat]
julia = "1.11"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
